name: URL Call

on:
  schedule:
    # 每10分钟运行一次
    - cron: "*/10 * * * *"
  workflow_dispatch: # 允许手动触发

permissions:
  contents: read

jobs:
  call-url:
    runs-on: ubuntu-latest

    steps:
      - name: Call URL
        run: |
          curl -X GET "https://caibai.yinziyang.free.hr/today"
        continue-on-error: true

      - name: Log timestamp
        run: |
          date '+%Y-%m-%d %H:%M:%S %Z'
          echo "URL called at $(date '+%Y-%m-%d %H:%M:%S %Z')"

      - name: Check response
        run: |
          response=$(curl -s -w "\n%{http_code}" "https://caibai.yinziyang.free.hr/json")
          status_code=$(echo "$response" | tail -n1)
          if [ "$status_code" != "200" ]; then
            echo "Error: HTTP status code $status_code"
            echo "Response: $response"
          fi
