name: Periodic URL Call

on:
  schedule:
    # 每10分钟运行一次
    - cron: "*/10 * * * *"
  # 可选：允许手动触发工作流
  workflow_dispatch:

jobs:
  call-url:
    runs-on: ubuntu-latest

    steps:
      - name: Call URL
        run: |
          curl -X GET "https://caibai.yinziyang.top/"
        # 如果需要检查响应状态
        continue-on-error: true

      # 可选：添加时间戳日志
      - name: Log timestamp
        run: |
          echo "URL called at $(date '+%Y-%m-%d %H:%M:%S')"
